// The ownership header every generated file carries, and the arithmetic behind
// it.
//
// The hash covers the body BELOW the header, for two reasons: a hash of the
// whole file would have to include itself, and reformatting the comment would
// otherwise read as a hand edit. Byte-stability is what makes any of this work
// — an emitter that varied its output would report every file as edited on the
// second run — so nothing here reads a clock, an environment or a disk.
import { createHash } from 'node:crypto';
import { ShipError } from '../log.mjs';
import { CONTRACT_VERSION } from './design-contract.mjs';

/** @type {(body: string) => string} */
export function bodyHash(body) {
	return createHash('sha256').update(body, 'utf8').digest('hex').slice(0, 8);
}

/** @type {(input: {source: string, hash: string}) => string} */
function headerFor({ source, hash }) {
	return [
		`// @generated by \`ship design build\` from ${source}`,
		`// @contract ${CONTRACT_VERSION}`,
		`// @hash ${hash}`,
		'// Edit freely. `ship design build` refuses to overwrite a changed file and',
		'// names it, rather than destroying your work. --force takes it back.',
		'',
		'',
	].join('\n');
}

/** @type {(body: string, opts: {source: string}) => string} */
export function withHeader(body, { source }) {
	return headerFor({ source, hash: bodyHash(body) }) + body;
}

const HASH_RE = /^\/\/ @hash ([0-9a-f]{8})$/m;
const SOURCE_RE = /^\/\/ @generated by `ship design build` from (.+)$/m;

/**
 * Split a generated file back into its header facts and its body. Null when the
 * file was not written by us.
 * @type {(text: string) => {hash: string, source: string, body: string}|null}
 */
export function parseHeader(text) {
	if (!text.startsWith('// @generated')) return null;
	const hash = HASH_RE.exec(text);
	const source = SOURCE_RE.exec(text);
	if (!hash || !source) return null;
	// The header ends at the first blank line; everything after it is the body.
	const end = text.indexOf('\n\n');
	if (end === -1) return null;
	return { hash: hash[1], source: source[1], body: text.slice(end + 2) };
}

/**
 * What writing this file would do.
 *
 * `foreign` and `edited` are separate because they need different advice: one
 * is a file somebody wrote by hand where we want to write, the other is our own
 * file somebody improved. Both refuse without --force.
 * @type {(text: string|null, body: string) => 'create'|'rewrite'|'edited'|'foreign'}
 */
export function classify(text, _body) {
	if (text === null || text === undefined) return 'create';
	const parsed = parseHeader(text);
	if (!parsed) return 'foreign';
	return parsed.hash === bodyHash(parsed.body) ? 'rewrite' : 'edited';
}

/**
 * A `ux.json` route to the expo-router file that serves it. Dynamic segments
 * pass through: `ship qa` cannot drive one, but that is a QA limitation, and
 * refusing to generate a legitimate screen is the wrong place to express it.
 * @type {(route: string) => string}
 */
export function routeToFile(route) {
	const trimmed = String(route ?? '').replace(/\/+$/, '');
	const segments = trimmed.split('/').filter(Boolean);
	if (segments.some((s) => s === '.' || s === '..'))
		throw new ShipError(`design build: route "${route}" escapes the app directory`, {
			hint: 'routes are literal expo-router paths, e.g. /paywall or /item/[id]',
		});
	return `app/${segments.length ? segments.join('/') : 'index'}.tsx`;
}
